prefix_v: n7m-eu-west-1-dev
region_v: eu-west-1

keypair_v: jps
instance_type_v: t4g.micro
# bastion_ami_v: ami-07448619ba6edca91  # amd64 (wintel) Ubuntu LTS
bastion_ami_v: ami-068257194ae9d7ebf   # arm64 Ubuntu LTS
owner_v: Jonathan Springer
