- hosts: all
  vars:
    state: absent
  gather_timeout: 30
- import_playbook: playbooks/ecs-down.yaml
- import_playbook: playbooks/postgis-down.yaml
- import_playbook: playbooks/efs-down.yaml
- import_playbook: playbooks/bastion-down.yaml
- import_playbook: playbooks/security-down.yaml
- import_playbook: playbooks/vpc-down.yaml
