ansible_user: ubuntu
prefix_v: n7m-eu-west-1-dev
region_v: eu-west-1
osm_continent_v: europe
osm_region_v: monaco
keypair_v: jps
owner_v: Jonathan Springer
ansible_ssh_private_key_file: ~/.ssh/jps.pem
access_key_v: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
secret_key_v: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
docker_credentials_arn: "arn:aws:secretsmanager:eu-west-1:179757322917:secret:docker_authentication-zC1Tiy"
secretsmanager_key: "arn:aws:kms:eu-west-1:179757322917:key/ce85f652-c132-446a-97b5-5bf47ee6686b"
n7m_domain: "n7m.test.stochastic-parrot.ie"
ca_certificate_arn: "arn:aws:acm:eu-west-1:179757322917:certificate/0fb8877a-9eac-4b45-a136-6028c4d5d06f"
